djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('serviceForm/', include('serviceForm.urls'))
]

serviceForm/urls.py
from django.urls import path
from serviceForm import views

app_name = 'serviceForm'
urlpatterns = [
    path('category/', views.category, name='category'),
    path('categoryCreate/', views.categoryCreate, name='categoryCreate'),
    path('categoryUpdate/<int:categoryid>/', views.categoryUpdate, name='categoryUpdate'),
    path('categoryDelete/<int:categoryid>/', views.categoryDelete, name='categoryDelete'),
    path('categoryRead/<int:categoryid>/', views.categoryRead, name='categoryRead'),
    path('form/', views.form, name='form'),
    path('formarea/', views.formarea, name='formarea'),


    # path('hospital/', views.hospital, name='hospital'),
]

serviceForm/forms.py
import datetime
from datetime import timedelta
from django import forms
from django.forms import ModelChoiceField
from smart_selects.form_fields import ChainedModelChoiceField

from serviceForm.models import Category, ServiceSheet, WorkState, Hospital, ContractType, MachineName, Machine, Factory, \
    Parts, Area


class CategoryForm(forms.ModelForm):
    categoryname = forms.CharField(label="類別名稱", required=True) # 資料表的欄位名稱

    class Meta:
        model = Category
        fields = ('categoryname', ) # 資料表的欄位名稱

# class HospitalForm(forms.ModelForm):
#為了讓同一個Parts class可以return不同值


class PartsgpnameModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.partsgpname


class PartsidModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.partsid


class MachineModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.machineid

# class SampleForm(forms.ModelForm):
#     class Meta:
#         model = Sample
#         fields = ('sheetid', 'hospital', 'machine')
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['machine'].queryset = Machine.objects.none()

class ServiceForm(forms.ModelForm):

    options = ( ("a", "A"), ("b", "B"),)
    sheetid = forms.CharField(label='單號', widget=forms.TextInput(attrs={'class':'form-control'}))
    emp = forms.CharField(label='填表人', widget=forms.TextInput(attrs={'class':'form-control'}))
    # area = forms.ModelChoiceField(Area.objects.all(), label='地區', widget=forms.Select(attrs={'class': 'form-control', 'id': 'area'}),initial="北區")
    date = forms.DateField(label='日期', input_formats='%Y-%m-%d', widget=forms.DateInput(attrs={'class': 'form-control','type':'date'}), initial=datetime.date.today)
    category = forms.ModelChoiceField(Category.objects.all(), label='項目總類', widget=forms.Select(attrs={'class': 'form-control'}), initial="一般維修")
    state = forms.ModelChoiceField(WorkState.objects.all(), label='狀態', widget=forms.Select(attrs={'class': 'form-control'}), initial="處理中")
    machineStop = forms.BooleanField(label='停機中', required=True)
    hospital = forms.ModelChoiceField(Hospital.objects.filter(areaid=1), label='醫院名稱', widget=forms.Select(attrs={'class': 'form-control', 'name': 'hospital', 'id':'hospital', 'onkeyup':'getdata();'}))
    receiver = forms.ModelChoiceField(Category.objects.filter(categoryname__startswith="醫用技術部"), label='收話人', widget=forms.Select(attrs={'class':'form-control'}), required=True) #要再改
    # mensent =forms.MultipleChoiceField(choices=options, label='處理人', widget=forms.SelectMultiple(attrs={'class':'form-control'}), required=True) #要再改
    mensent = forms.ModelChoiceField(Category.objects.filter(categoryname__startswith="保"), label='處理人', widget=forms.Select(attrs={'class':'form-control'}), required=True) #要再改
    contractType = forms.ModelChoiceField(ContractType.objects.all(), label='合約型態', widget=forms.Select(attrs={'class': 'form-control'}), initial="W")
    # machineName = forms.ModelChoiceField(Machine.objects.select_related('hospitalid__areaid').filter(hospitalid__areaid=1).distinct(), label='機器名稱', widget=forms.Select(attrs={'class': 'form-control', 'id':'machinename'}), initial="TOMO")
    machineName = forms.ModelChoiceField(MachineName.objects.all(), label='機器分類', widget=forms.Select(attrs={'class': 'form-control', 'id':'machinename'}))
    machineid = MachineModelChoiceField(queryset=Machine.objects.select_related('hospitalid__areaid').filter(hospitalid__areaid=1), label='機器型號', widget=forms.Select(attrs={'class': 'form-control'}))
    callcont = forms.CharField(widget=forms.Textarea, label='叫修內容')
    brokenitems= forms.CharField(label='故障項目', widget=forms.TextInput(attrs={'class':'form-control'}))
    facid = forms.ModelChoiceField(Factory.objects.all(), label='更換零件(工廠碼)', widget=forms.Select(attrs={'class': 'form-control'}), initial="T011") #不入資料庫
    partsgpname = PartsgpnameModelChoiceField(queryset=Parts.objects.all(), label='(物料)', widget=forms.Select(attrs={'class': 'form-control'})) #不入資料庫
    partsid = PartsidModelChoiceField(queryset=Parts.objects.all(), label='', widget=forms.Select(attrs={'class': 'form-control','id':'partsid', 'name': 'partsid'})) #不入資料庫
    parts = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','id':'partsall', 'type':'text'})) #入資料庫 零件號
    calltime = forms.TimeField(label='叫修時間', widget=forms.TimeInput(attrs={'class':'form-control', 'type': 'time'}))
    arrtime = forms.TimeField(label='到達時間', widget=forms.TimeInput(attrs={'class':'form-control', 'type': 'time'}))
    fixtime = forms.TimeField(label='維修時間', widget=forms.TimeInput(attrs={'class':'form-control', 'type': 'time', 'name':'input-time', 'id':'start-time'}))
    repairedtime = forms.TimeField(label='修復完成時間', widget=forms.TimeInput(attrs={'class':'form-control', 'type': 'time', 'id':'end-time'}))
    repairdur = forms.DurationField(label='維修時數', widget=forms.TextInput(attrs={'class':'form-control', 'id':'total-hours'})) #auto-count
    machinestpdur = forms.FloatField(label='停機時數', widget=forms.TextInput(attrs={'class':'form-control'}),)
    repaircont = forms.CharField(label='檢修內容', widget=forms.TextInput(attrs={'class':'form-control'}))
    note = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','cols': 80, 'rows': 1}), label='備註')


    class Meta:
        model = ServiceSheet  #models.py
        fields = '__all__'
        # fields = (' sheetid','empid', 'areaid', 'categoryid', 'stateid', 'date', 'machineStop', 'hospitalid', 'receiver', 'mensent', 'contractid', 'machinename', 'machineid', 'callcont', 'brokenitems', 'partsid', 'calltime', 'arrivetime', 'fixingtime', 'repairtime', 'repairdur', 'machinestpdur', 'repaircont', 'note', ) # 資料表的欄位名稱

serviceForm/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from serviceForm.forms import CategoryForm, ServiceForm
from serviceForm.models import Category, Machine

from django.core import serializers
from django.views.generic import ListView, CreateView, UpdateView

# Create your views here.

#要有default pre-populated with initial values


def category(request):
    categories = Category.objects.all()
    return render(request, 'admin/category.html', {'categories': categories})


def categoryCreate(request):
    if request.method == 'GET':
        categoryForm = CategoryForm()
        return render(request, 'admin/categoryCreate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST)
        if not categoryForm.is_valid():
            return render(request, 'admin/categoryCreate.html', {'categoryForm': categoryForm})
        categoryForm.save()
        messages.success(request, '新增成功')
        return redirect(reverse('serviceForm:category'))  # /serviceForm/category/


def categoryUpdate(request, categoryid):
    category = get_object_or_404(Category, categoryid=categoryid)  # Category.objects.get(categoryid=id)
    if request.method == 'GET':
        categoryForm = CategoryForm(instance=category)
        return render(request, 'admin/categoryUpdate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST, instance=category)
        if not categoryForm.is_valid():
            return render(request, 'admin/categoryUpdate.html', {'categoryForm': categoryForm})
        categoryForm.save()
        messages.success(request, '修改成功')
        return redirect(reverse('serviceForm:category'))


def categoryDelete(request, categoryid):
    category = get_object_or_404(Category, categoryid=categoryid)
    if request.method == 'POST':
        category.delete()
        messages.success(request, '刪除成功')
    return redirect(reverse('serviceForm:category'))


def categoryRead(request, categoryid):
    category = get_object_or_404(Category, categoryid=categoryid)
    return render(request, 'admin/categoryRead.html', {'category': category})


def form(request):
    # return render(request, 'form.html')
    if request.method == 'GET':
        serviceForm = ServiceForm()
        return render(request, 'form.html', {'serviceForm': serviceForm})
    elif request.method == 'POST':
        serviceForm = ServiceForm(request.POST)
        # emplist =
        if not serviceForm.is_valid():
            return render(request, 'form.html', {'serviceForm': serviceForm})

        serviceForm.save()
        return redirect(reverse('serviceForm:form'))

def formarea(request):
    return render(request, 'formarea.html')

serviceForm/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{#    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">#}
    <title>叫修紀錄</title>
    {% block head %}
    {% endblock %}
</head>
<body>
{% include 'main/nav.html' %}
{% if messages %}
  <div>
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}-{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>

serviceForm/templates/main/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 30px">
  <a class="navbar-brand" href="{% url 'serviceForm:formarea' %}">首頁</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'serviceForm:category' %}">Link <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          選單管理
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">醫院</a>
          <a class="dropdown-item" href="#">機器</a>
{#          <a class="dropdown-item" href="#">項目總類</a>#}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'serviceForm:category' %}">項目總類</a>
          <a class="dropdown-item" href="#">故障項目</a>
          <a class="dropdown-item" href="#">檢修內容</a>
        </div>
      </li>
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#">Disabled</a>#}
{#      </li>#}
    </ul>

  </div>
</nav>